# BUG? doesn't work: library(anndata)
# BUG? doesn't work: library(AnnotationHub)
# BUG? doesn't work: library(DoubletFinder)
# BUG? doesn't work: library(scRNAseq)
# BUG? doesn't work: library(SeuratData)
# BUG? doesn't work: library(SingleR)
# BUG? doesn't work: library(slingshot)
# BUG? doesn't work: library(tradeSeq)
# BUG? doesn't work: library(TSCAN)
# BUG? doesn't work: library(velociraptor) # cannot install python packages
# BUG? doesn't work: library(zellkonverter)
library(BiocParallel)
library(dplyr)
library(DropletUtils)
library(ggplot2)
library(Matrix)
library(patchwork)
library(pheatmap)
library(scater)
library(scran)
library(scry)
library(scuttle)
library(Seurat)
library(SoupX)
