---
title: "scRNAseq for Gamm"
output: pdf_document
---

# Abstract
We are trying to create good pig retenoids. We want to see how good it is by comparing scRNA expression to that of human cells. 
We describe how good we did. ...

# Results

## cell type predictions: scPred vs Seurat mapping

- bipolar and photoreceptors predicted well by both scPred and Seurat mapping.
- Muller glia cells predicted better by seurat mapping
- both predicted majority of ganglion cells as microglia
- amacrine, horizontal, midbrain and progentior cells not predicted in pig
``` {r}
make_figure_1()
```
figure caption: Figure 1 compares scPred and Seurat Mapping predictions
A. umap of scpred prediction vs manual annotation
B. umap of seurat mapping prediciton vs manual
C. table of scpred prediction vs manual
D. table of seurat mapping prediciton vs manual

# Discussion

# Conclusions

# Methods

## Data
We are using pig and human data.

- pig data is from Gamm lab
    - sample 1 is retinal organoid from day XX
    - sample 2 is retinal organoid from day 125
    - each sample was run on two flow cell lanes for technical replicates
- human data is from Reh 2020, GSE142526
    - one sample from human retinal organoid day 205
    - run on four flow cell lanes
- TODO Get more Data
    - Cowan
    - ?
    - Mouse ?


## Star solo
To map the reads we used star solo

- Building the index
    - pig genome: Sus_scrofa_berkshire.Berkshire_pig_v1.109 from Ensemble
    - human genome: Homo_sapiens.GRCh38.108 from Ensemble
- Mapping
    - parameter choice guided by star solo documentation (Ref)
        - empty drops filtered
        - EM used for multimapping
        - 1 mismatch for UMI count allowed
    - TODO: output path and n threads

## Soup X
To normalize for ambient mRNA
- soup X
    - compare raw and filtered counts to estimate the amount of ambient mRNA. 
    - then adjust counts accordingly
- parameters are umap method and dimensions
- TODO: ? refactor (leverage run_umap code)

## Dbl Remover
To remove droplets that contain two or more cells

- Doublet Finder

## Mitochondrial gene filtering

## Normalization

## Feature selection